### PR TITLE
feat: show contact status colour in PostChips

### LINKED ISSUE #531: More clearly indicate a contact is closed or open
When selecting from a list of contacts for _Assigned to_ or _Subassigned to_, the web app uses a "light gray" font color to indicate a contact record is **closed**. A similar way to indicate a contact as closed or open when looking at a list of contacts on the mobile app would be helpful.

Screen Shot 2020-12-17 at 2 46 00 AM

### PR DESCRIPTION
**Pull request by squigglybob**
resolves #531

### CODE REVIEW

**Comment by squigglybob** [comment]
@mikeallbutt @zdmc23 
how does this look? let me know if I'm on the right kindof track

image

Since this ticket was first made, the contact select fields have had contact colours added to them, so I've been moving towards that way

image

**Comment by zdmc23** [comment]
@squigglybob Nice! I *do* worry that since status color is configurable, coloring the entire chip could present a problem if they chose black for archived or something. How about if the left rounded side was the status color and the 'body' of chip was consistent?

**Comment by squigglybob** [comment]
yeah I was wondering about that too 🙂

**Review by zdmc23 — CHANGES_REQUESTED** [review]
Looks good (thx for componetizing the StatusBorder!), but the FlatList patch is still included

**Comment by squigglybob** [comment]
One thing to note, is that the Chip can  already cope well with black as the background as show on the group status screen

Screenshot_20220915-143420_2

I can still do a left patch, and that would also match the web app more closely as they use a left bar to denote the colour

**Comment by squigglybob** [comment]
This is how it looks now...
Screenshot_20220915-164926_2

**Review by zdmc23 — APPROVED** [review]

**Pull request merged**
