### PR TITLE
Sprint 10

### PR DESCRIPTION
**Pull request by jl0325**
#29

### CODE REVIEW

**Comment by jl0325** [comment]
I'm using the same, like development brach

**Comment by zdmc23** [comment]
Something is different bc the `prettier` configurations should result in multi-line imports:

Screenshot from 2019-11-26 21-27-15

**Comment by jl0325** [comment]
@zdmc23, 
The "prettier" is launched when the commit is generated automatically and runs under the settings that the development branch has. 

Captura de Pantalla 2019-11-27 a la(s) 8 12 09 a  m

Captura de Pantalla 2019-11-27 a la(s) 8 00 22 a  m

**Comment by jl0325** [comment]
> Something is different bc the `prettier` configurations should result in multi-line imports:
> 
> Screenshot from 2019-11-26 21-27-15

In this case, I remove Containe, Content, Footer and  FooterTab. Then, eliminating these changes the way of presenting for the formatter configuration because it is under the rule of maximum number of characters per line

**Comment by zdmc23** [comment]
Thx for the explanation; I am merging...

**Pull request merged**
