### PR TITLE
Resolves #686 - Dates in logs are now user friendly

### LINKED ISSUE #686: Dates in logs are not user friendly
The date in the logs are like `Baptism Date: {1654111560} ` and need to be shown in the same way the app user wants depending on their device settings ie. dd-mm-yyyy or mm-dd-yyyy

### PR DESCRIPTION
**Pull request by jhenterprise**
Resolves #686 - Dates in logs are now user friendly
disciple_tools_activity_log2

### CODE REVIEW

**Review by zdmc23 — CHANGES_REQUESTED** [review]
Hi @jhenterprise , your PR has changes for `package.json` and `package-lock.json`, but it looks like those files did not need to change for this fix.  Could you please `git pull` the latest versions of those files and remove from PR?

Per the actual changes, the regex approach is very nice, but it looks like we're applying it to any Activity Log but naming it "baptism" specific.  @mikeallbutt may be able to confirm whether there are any other occurrences of timestamps rather than dates, but perhaps we should just drop the word `baptism` and refer to it as `timestampToDate` instead?

Thx!

**Comment by zdmc23** [comment]
Hi @jhenterprise , the package files still remain in your PR, would you kindly remove those.  Also, the PR in front of yours made a change to `components/Card/ActivityLogCard.js`, so please pull the latest version of that file and merge your new changes into it and resubmit.  I will merge your PR next.  Thx!

**Comment by jhenterprise** [comment]
Hi @zdmc23, oh I just noticed, how this happen. Did I clone from the wrong branch (development)? How can I fix it? I again pull from the development branch?

**Comment by zdmc23** [comment]
No worries, you pulled from the correct branch, but we have ongoing development and I merged another PR since time you cloned.

Yes, go ahead and pull to merge the changes. Thx!

**Pull request closed without merging**
